import hashlib,json,shutil,subprocess,tempfile,unittest
from pathlib import Path
from helpers import *
class MigrationTests(unittest.TestCase):
 def test_check_non_mutating(self):
  v=base();source(v);wiki(v);before={str(p.relative_to(v)):hashlib.sha256(p.read_bytes()).hexdigest() for p in v.rglob('*') if p.is_file()};r=run(v,'migrate','--check');after={str(p.relative_to(v)):hashlib.sha256(p.read_bytes()).hexdigest() for p in v.rglob('*') if p.is_file()};self.assertEqual(r.returncode,0);self.assertEqual(before,after);shutil.rmtree(v)
 def test_apply_preserves_body(self):
  v=base();p=wiki(v);marker='Durable architecture separates evidence and memory.';r=run(v,'migrate','--apply');self.assertEqual(r.returncode,0,r.stdout+r.stderr);self.assertIn(marker,p.read_text());shutil.rmtree(v)
 def legacy(self,root,path='Wiki/Concepts/legacy.md',title='Legacy Architecture'):
  p=root/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(fm({'title':title,'tags':['concept'],'created':DATE,'updated':DATE},'\n# Legacy\n\nBODY MARKER\n'));return p
 def test_apply_transforms_legacy_and_creates_structure(self):
  v=Path(tempfile.mkdtemp());p=self.legacy(v);(v/'tests').mkdir();r=run(v,'migrate','--apply');self.assertEqual(r.returncode,0,r.stdout+r.stderr);d,b=parse_fixture(p);self.assertEqual((d['schema_version'],d['type'],d['id']),(2,'concept','concept-legacy-architecture'));self.assertNotIn('tags',d);self.assertIn('BODY MARKER',b);self.assertEqual(json.loads((v/'Schema/version.json').read_text())['knowledge_os_schema'],2);self.assertTrue((v/'Wiki/catalog.jsonl').is_file());shutil.rmtree(v)
 def test_apply_moves_unambiguous_root_note_and_hashes_id_collision(self):
  v=Path(tempfile.mkdtemp());(v/'.obsidian').mkdir();(v/'tests').mkdir();self.legacy(v,'first.md','Same');self.legacy(v,'second.md','Same');r=run(v,'migrate','--apply');self.assertEqual(r.returncode,0,r.stdout+r.stderr);notes=sorted(p for p in (v/'Wiki/Concepts').glob('*.md') if p.name!='index.md');ids=[parse_fixture(p)[0]['id'] for p in notes];self.assertIn('concept-same',ids);expected='concept-same-'+hashlib.sha256(b'concept\nsecond.md').hexdigest()[:6];self.assertIn(expected,ids);self.assertTrue(all('BODY MARKER' in p.read_text() for p in notes));shutil.rmtree(v)
 def test_apply_matches_planned_id_when_existing_id_sorts_later(self):
  v=Path(tempfile.mkdtemp());(v/'.obsidian').mkdir();(v/'tests').mkdir();self.legacy(v,'a.md','Same');p=self.legacy(v,'z.md','Existing');rewrite(p,lambda d:d.update(id='concept-same'));plan=json.loads(run(v,'migrate','--check').stdout);planned=next(x['set']['id'] for x in plan['frontmatter_transformations'] if x['path']=='a.md');r=run(v,'migrate','--apply');self.assertEqual(r.returncode,0,r.stdout+r.stderr);ids=[parse_fixture(p)[0]['id'] for p in (v/'Wiki/Concepts').glob('*.md') if p.name!='index.md'];self.assertEqual(ids.count('concept-same'),1);self.assertIn(planned,ids);shutil.rmtree(v)
 def test_check_reports_plan_without_mutation(self):
  v=Path(tempfile.mkdtemp());self.legacy(v);before=pbytes(v);r=run(v,'migrate','--check');plan=json.loads(r.stdout);self.assertEqual(r.returncode,0);self.assertEqual(plan['repository_class'],'C');self.assertTrue(plan['frontmatter_transformations']);self.assertTrue(plan['create']);self.assertEqual(before,pbytes(v));shutil.rmtree(v)
 def test_schema_two_check_ignores_templates(self):
  v=base();source(v);wiki(v,sources=['Raw/Sources/evidence.md']);template=v/'_templates/concept-note.md';template.parent.mkdir();template.write_text((v/'Wiki/Concepts/architecture.md').read_text());r=run(v,'migrate','--check');plan=json.loads(r.stdout);self.assertEqual(r.returncode,0);self.assertEqual(plan['repository_class'],'D');self.assertEqual(plan['move'],[]);self.assertEqual(plan['frontmatter_transformations'],[]);self.assertEqual(plan['ambiguous'],[]);self.assertTrue(plan['safe_to_apply']);shutil.rmtree(v)
 def test_apply_refuses_dirty_git_and_creates_clean_checkpoint(self):
  v=Path(tempfile.mkdtemp());self.legacy(v);(v/'tests').mkdir();subprocess.run(['git','init','-q'],cwd=v,check=True);subprocess.run(['git','config','user.email','test@example.invalid'],cwd=v,check=True);subprocess.run(['git','config','user.name','Test'],cwd=v,check=True);subprocess.run(['git','add','.'],cwd=v,check=True);subprocess.run(['git','commit','-qm','legacy'],cwd=v,check=True);(v/'dirty.txt').write_text('dirty');dirty=run(v,'migrate','--apply');self.assertNotEqual(dirty.returncode,0);self.assertFalse((v/'Schema/version.json').exists());(v/'dirty.txt').unlink();clean=run(v,'migrate','--apply');self.assertEqual(clean.returncode,0,clean.stdout+clean.stderr);tags=subprocess.run(['git','tag','--list','knowledge-os-pre-migrate-*'],cwd=v,text=True,capture_output=True,check=True).stdout.splitlines();self.assertEqual(len(tags),1);shutil.rmtree(v)
 def test_apply_rolls_back_git_worktree_when_validation_fails(self):
  v=Path(tempfile.mkdtemp());self.legacy(v);(v/'tests').mkdir();(v/'tests/test_fail.py').write_text('import unittest\nclass Failure(unittest.TestCase):\n def test_fail(self): self.fail("boom")\n');subprocess.run(['git','init','-q'],cwd=v,check=True);subprocess.run(['git','config','user.email','test@example.invalid'],cwd=v,check=True);subprocess.run(['git','config','user.name','Test'],cwd=v,check=True);subprocess.run(['git','add','.'],cwd=v,check=True);subprocess.run(['git','commit','-qm','legacy'],cwd=v,check=True);before={p.relative_to(v).as_posix():p.read_bytes() for p in v.rglob('*') if p.is_file() and '.git' not in p.parts};r=run(v,'migrate','--apply');self.assertNotEqual(r.returncode,0);after={p.relative_to(v).as_posix():p.read_bytes() for p in v.rglob('*') if p.is_file() and '.git' not in p.parts};self.assertEqual(before,after);self.assertEqual(subprocess.run(['git','status','--porcelain'],cwd=v,text=True,capture_output=True,check=True).stdout,'');shutil.rmtree(v)
if __name__=='__main__':unittest.main()
